sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
    - echo "127.0.0.1   example.com" | sudo tee -a /etc/hosts 
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
    - sudo make eXist && sudo ./.temp/eXist-run.sh
script:
- prove -v
