sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
    hosts:
        - example.com
before-install:
    - sudo cat /etc/hosts
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
    - sudo make eXist && sudo ./.temp/eXist-run.sh
script:
- prove -v
