sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
- git clone https://github.com/ingydotnet/test-more-bash.git 
install:
- make && ./.temp/run.sh
script:
- prove
