sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
        - expect
before_install:
- echo "install latest eXist release"
- touch config
install:        
    - make build
before_script:
    - cd $HOME/eXist 
    - pwd
    - java -Djava.endorsed.dirs=lib/endorsed -jar start.jar jetty & 
script:
    - true
before_script:
    - cd $HOME/eXist 
    - pwd
    - java -Djava.endorsed.dirs=lib/endorsed -jar start.jar shutdown -u admin -p admin 
