sudo: false
language: java
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
        - expect
        - make
before_install:
- which java
- which expect
- which prove
- echo "install latest eXist release"
- touch config
- make help
install:
    - true
script:
    - true
