sudo: false
language: java
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
        - expect
before_install:
- which java
- which expect
- which prove
- which make
- echo "install latest eXist release"
- touch config
install:
    - make build
script:
    - true
