sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before_install:
      - sudo source config; echo "127.0.0.1  $(echo ${DEPLOY} | cut -d/ -f2 )" >> /etc/hosts
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
script:
    - prove -v  t/nginx.t

