sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before_install:
      - sudo source config;REPO="$(echo ${DEPLOY} | cut -d/ -f2 )";[ -z "$( echo $(< /etc/hosts) | grep ${REPO})" ] && echo "127.0.0.1  ${REPO}" >> /etc/hosts
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
script:
    - prove -v  t/nginx.t

