sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
- true
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
    - sudo make eXist && sudo ./.temp/eXist-run.sh
script:
- prove -v
