sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
- true
install:
- make && ./.temp/eXist-run.sh
- sudo ./.temp/nginx-run.sh
script:
- prove -v
