sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y davfs2
install:
    - sudo chmod 4750 /usr/sbin/mount.davfs && sudo usermod -aG davfs2 ${SUDO_USER} 
    - sudo make nginx && sudo ./.temp/nginx-run.sh
    - sudo make eXist && sudo ./.temp/eXist-run.sh
script:
    - prove -v

