sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before_install:
      - true
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
script:
    - prove -v  t/nginx.t

