sudo: required
dist: trusty
language: java
env:
   - SLIMERJSLAUNCHER=$(which firefox)
addons:
    apt:
        packages:
        - expect
        - nodejs
before_install:
   - which node
   - which perlbrew
   - perlbrew list-modules
   - which cpanm
install:
  - npm install
  - sudo make build --jobs=2
  - sudo ./.temp/nginx-run.sh
  - sudo ./.temp/eXist-run.sh
  - sudo make deploy && ./.temp/deploy.sh
script:
  - prove -v - < t/travis.txt

