sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
        - nodejs
before_install:
   - which node 
   - which perlbrew  
   - perlbrew list-modules 
install:
  - npm install nightmarejs 
  - sudo make build --jobs=2  
  - sudo ./.temp/nginx-run.sh
  - sudo ./.temp/eXist-run.sh
  - sudo make deploy && ./.temp/deploy.sh 
script:
  - prove -v - < t/travis.txt

