sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
- true
install:
    - sudo make build-nginx && sudo ./.temp/nginx-run.sh
script:
- prove -v
