sudo: required
dist: trusty
language: java
jdk:
    - oraclejdk8
addons:
    apt:
        packages:
        - expect
before_install:
- echo "install latest eXist release"
- touch config
install:
    - make build
before_script:
    - cd $HOME/eXist
    - pwd
    - java -Djava.endorsed.dirs=lib/endorsed -jar start.jar jetty & 
    - sleep 3
script:
    - curl -I -s -f 'http://localhost:8080/' 
    - cd $HOME/eXist
    - echo 'sm:is-authenticated()' |  java -Djava.endorsed.dirs=lib/endorsed -jar start.jar client -sqx -u admin -P admin
after_script:
    - cd $HOME/eXist
    - pwd
    - java -Djava.endorsed.dirs=lib/endorsed -jar start.jar shutdown -u admin -p admin
