sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before-install:
    - true
install:
    - true
before_script:
- git clone https://github.com/ingydotnet/test-more-bash.git 
script:
- make build
- cd $HOME/eXist
- java -Djava.endorsed.dirs=lib/endorsed -Djava.net.preferIPv4Stack=true -jar start.jar jetty &
- while [[ -z "$(curl -I -s -f 'http://127.0.0.1:8080/')" ]] ; do sleep 5 ; done
- cd ../
- pwd
- make test
after_script:
- cat webapp/WEB-INF/logs/exist.log | tail -n 5
- cd $HOME/eXist
- java -Djava.endorsed.dirs=lib/endorsed -jar start.jar shutdown -u admin -p admin
