sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y davfs2          
      - expect -d -c "sudo spawn  dpkg-reconfigure davfs2 -freadline; expect \"Should\"; send \"y\\n\"; interact" 
install:
    - sudo make nginx && sudo ./.temp/nginx-run.sh
    - sudo make eXist && sudo ./.temp/eXist-run.sh
script:
- prove -v t/test.t
