#!/usr/bin/env bash 
source config

P=admin
if [ -e ${ACCESS_TOKEN_PATH} ] ;then P="$(<${ACCESS_TOKEN_PATH})";fi
TEST_MORE_PATH='test-more-bash'
BASHLIB="$(
 find $TEST_MORE_PATH -type d |
 grep -E '/(bin|lib)$' |
 xargs -n1 printf "%s:")"

PATH="$BASHLIB$PATH"

source bash+ :std
